image: "tiangolo/node-frontend"

cache:
    paths:
        - node_modules/

deploy_stage:
    stage: deploy
    environment: Stage
    only:
        - master
    script:
        - npm install
        - ng build --prod